# Generated by Django 6.0.1 on 2026-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('ex_date', models.DateField(db_index=True)),
                ('action_type', models.CharField(choices=[('DIVIDEND', 'Dividend'), ('SPLIT', 'Split'), ('BONUS', 'Bonus'), ('OTHER', 'Other')], max_length=10)),
                ('factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('raw_purpose', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'ex_date'], name='core_corpor_symbol_b28e92_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('trade_date', models.DateField(db_index=True)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'trade_date'], name='core_stockp_symbol_327610_idx')],
                'unique_together': {('symbol', 'trade_date')},
            },
        ),
    ]
